services:
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      #
      - ./vol/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      #
      - ./vol/caddy/data:/data
      - ./vol/caddy/config:/config

    networks:
      - caddy-universe
      - caddy-outline



networks:

  caddy-universe:
    name: caddy-universe
    driver: bridge

  caddy-outline:
    name: caddy-outline
    external: true